package com.cineverse.gateway.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;

/**
 * JwtUtil - Validates JWT tokens from incoming requests
 * 
 * The token is generated by authservice.
 * Gateway validates the token before forwarding the request.
 */
@Component
public class JwtUtil {
    
    // Secret key for validating JWT tokens (same as authservice)
    @Value("${app.jwt.secret}")
    private String jwtSecret;
    
    /**
     * Validate JWT token
     * 
     * This method checks:
     * 1. Token signature is valid (created with same secret key)
     * 2. Token has not expired
     * 3. Token can be parsed successfully
     * 
     * @param token: JWT token string (without "Bearer " prefix)
     * @return: true if token is valid, false otherwise
     */
    public boolean validateToken(String token) {
        try {
            // Create SecretKey from the secret string
            SecretKey key = Keys.hmacShaKeyFor(jwtSecret.getBytes());
            
            // Parse the token
            // If token signature is invalid or token is expired,
            // an exception will be thrown
            Jwts.parserBuilder()
                    .setSigningKey(key)
                    .build()
                    .parseClaimsJws(token);
            
            // If parsing succeeds without exception, token is valid
            return true;
        } catch (Exception e) {
            // If any exception occurs, token is invalid
            System.out.println("JWT Token Validation Error: " + e.getMessage());
            return false;
        }
    }
    
    /**
     * Extract email (subject) from JWT token
     * 
     * This is useful for logging which user is accessing which endpoint
     * 
     * @param token: JWT token string
     * @return: Email of the user
     */
    public String getEmailFromToken(String token) {
        try {
            SecretKey key = Keys.hmacShaKeyFor(jwtSecret.getBytes());
            Claims claims = Jwts.parserBuilder()
                    .setSigningKey(key)
                    .build()
                    .parseClaimsJws(token)
                    .getBody();
            
            // Subject (sub) contains the email
            return claims.getSubject();
        } catch (Exception e) {
            return null;
        }
    }
    
    /**
     * Extract role from JWT token
     * 
     * This can be used for role-based routing in future
     * 
     * @param token: JWT token string
     * @return: User's role (USER, ADMIN, etc.)
     */
    public String getRoleFromToken(String token) {
        try {
            SecretKey key = Keys.hmacShaKeyFor(jwtSecret.getBytes());
            Claims claims = Jwts.parserBuilder()
                    .setSigningKey(key)
                    .build()
                    .parseClaimsJws(token)
                    .getBody();
            
            // Role is stored as a claim
            return claims.get("role", String.class);
        } catch (Exception e) {
            return null;
        }
    }
}
